<a href="https://colab.research.google.com/github/bkaanulgen/TCMB-Kur/blob/main/TCMB_Kur.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install evds

from evds import evdsAPI
import pandas as pd
import numpy as np
evds = evdsAPI('kvlUQV03Zp')

term = '2023-07'

term_year = term[:4]
term_month = term[-2:]
term_end_day = pd.Period('{}-01-{}'.format(term_month, term_year), freq='M').end_time.day

start_date_str = '01-{}-{}'.format(term_month, term_year)
end_date_str = '{}-{}-{}'.format(term_end_day, term_month, term_year)

data_list = ['TP.DK.AUD.A.YTL', 'TP.DK.CAD.A.YTL', 'TP.DK.CHF.A.YTL', 'TP.DK.DKK.A.YTL', 'TP.DK.EUR.A.YTL', 'TP.DK.GBP.A.YTL', 'TP.DK.JPY.A.YTL', 'TP.DK.KWD.A.YTL', 'TP.DK.NOK.A.YTL', 'TP.DK.SAR.A.YTL', 'TP.DK.SEK.A.YTL', 'TP.DK.USD.A.YTL']

df_evds_avg = evds.get_data(data_list, startdate = start_date_str, enddate = end_date_str, aggregation_types='avg', frequency = 5)
df_evds_end = evds.get_data(data_list, startdate = start_date_str, enddate = end_date_str)

df_avg = pd.DataFrame()
df_avg['Döviz'] = data_list
df_avg['Döviz'] = df_avg['Döviz'].apply(lambda x: x[6:9])
df_avg[term] = list(df_evds_avg.iloc[0, 1:])
df_avg = df_avg.sort_values('Döviz').set_index('Döviz')

df_avg['Ortalama'] = np.round(df_avg[term] * 1_000_000).astype(int).astype(str)
df_avg.loc['JPY', 'Ortalama'] = '{:.2f}'.format(np.round(df_avg.loc['JPY', term] * 10_000, 2))

df_evds_end_fix = df_evds_end
df_evds_end_fix = df_evds_end_fix[df_evds_end_fix.iloc[:,1].notnull()].sort_values('Tarih', ascending = False).head(1)

df_end = pd.DataFrame()
df_end['Döviz'] = data_list
df_end['Döviz'] = df_end['Döviz'].apply(lambda x: x[6:9])
df_end[term] = list(df_evds_end_fix.iloc[0, 1:])
df_end = df_end.sort_values('Döviz').set_index('Döviz')

df_end['Yıl Sonu'] = np.round(df_end[term] * 1_000_000).astype(int).astype(str)
df_end.loc['JPY', 'Yıl Sonu'] = '{:.2f}'.format(np.round(df_end.loc['JPY', term] * 10_000, 2))

Requirement already satisfied: evds in /usr/local/lib/python3.10/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from evds) (1.5.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from evds) (2.27.1)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from evds) (1.26.16)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evds) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evds) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas->evds) (1.22.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->evds) (2023.7.22)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->evds) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->evds) (3.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->evds) (1.16.0)

# Ortalama Kur

In [ ]:
df_avg

         2023-07   Ortalama
Döviz
AUD    17.753810   17753810
CAD    19.969329   19969329
CHF    30.140338   30140338
DKK     3.913633    3913633
EUR    29.204086   29204086
GBP    33.961048   33961048
JPY    18.687071  186870.71
KWD    85.603543   85603543
NOK     2.561852    2561852
SAR     7.043848    7043848
SEK     2.499510    2499510
USD    26.422738   26422738

# Yıl Sonu Kuru

In [ ]:
df_end

       2023-07   Yıl Sonu
Döviz
AUD    17.8721   17872100
CAD    20.3319   20331900
CHF    30.8767   30876700
DKK     3.9614    3961400
EUR    29.5700   29570000
GBP    34.4740   34474000
JPY    19.2755  192755.00
KWD    87.2182   87218200
NOK     2.6372    2637200
SAR     7.1818    7181800
SEK     2.5444    2544400
USD    26.9394   26939400